# Generated by Django 4.1.7 on 2023-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='pics'),
        ),
    ]
