# Generated by Django 4.1.7 on 2023-06-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModelform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=254)),
                ('profile_pic', models.ImageField(help_text='200kb image', upload_to='')),
                ('other_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('phone_number', models.CharField(max_length=11)),
                ('state_of_origin', models.CharField(max_length=20)),
                ('local_government_area_of_origin', models.CharField(max_length=70)),
                ('scheme_name', models.CharField(max_length=100)),
                ('year_of_application', models.DateField()),
            ],
        ),
    ]
