# Generated by Django 4.1.7 on 2023-06-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profilemodelform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodelform',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='local_government_area_of_origin',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='scheme_name',
        ),
        migrations.RemoveField(
            model_name='profilemodelform',
            name='state_of_origin',
        ),
        migrations.AlterField(
            model_name='profilemodelform',
            name='year_of_application',
            field=models.CharField(max_length=20),
        ),
    ]
