# Generated by Django 4.1.7 on 2023-06-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profilemodelform_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModelform',
        ),
    ]
